# Generated by Django 4.2.5 on 2023-12-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0002_alter_file_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="ended",
            new_name="end",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file",
        ),
        migrations.AddField(
            model_name="file",
            name="data",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
