# Generated by Django 4.2.5 on 2023-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='private_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='public_key',
            field=models.BinaryField(),
        ),
    ]
