# Generated by Django 4.2.5 on 2023-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0003_alter_space_private_key_alter_space_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="ended",
            field=models.BooleanField(default=False),
        ),
    ]
